name: base
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyterlab==4.0.6
  - conda-libmamba-solver=23.7.0
  - lazygit 
  - sqlalchemy 
  - jupyter-resource-usage 
  - jupyter-dash 
  - plotly 
  - jupyterlab_code_formatter 
  - isort 
  - black 
  - flake8  
  - jupyter-server-proxy 
  - jupyterlab-git 
  - ipympl
  - numba 
  - jupyterlab_execute_time 
  - jupytext 
  - jupyterlab-spellchecker
  - jupyter-vscode-proxy 
  - r-languageserver 
  - nb_conda_kernels 
  - ipykernel
  - lux-api
  - argcomplete 
  - jedi 
  - jedi-language-server 
  - radian 
  - r-httpgd
  - r-base 
  - r-caret 
  - r-crayon 
  - r-devtools 
  - r-e1071 
  - r-forecast 
  - r-hexbin 
  - r-htmltools 
  - r-htmlwidgets 
  - r-irkernel 
  - r-nycflights13 
  - r-randomforest 
  - r-rcurl 
  - r-rmarkdown 
  - r-rodbc 
  - r-rsqlite 
  - r-shiny 
  - r-tidymodels 
  - r-tidyverse 
  - rpy2 
  - unixodbc
  - jupyterlab-night
  - trino-python-client