name: DARE Jupyter Container

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/DARE-Jupyter-Container.yaml'
      - 'containers/jupyterlab/**'
    # Make sure all workflows that are "required checks" for a given
    # branch protection rule have the same paths: and branches-ignore:
    # filters. Otherwise, you can end up in a deadlock waiting on a
    # required check that will never be executed.
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'main'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/DARE-Jupyter-Container.yaml'
      - 'containers/jupyterlab/**'

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Needed to generate releases safely
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  nexus-container:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v5.0.0-containers
    with:
      job-name: DARE-Jupyter-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: dare/hive
      release-tag-format: 'DARE-Hive-Container-${version}'
      notation-cert: ${{ vars.NOTATION_CERT }}
      build-file: containers/jupyterlab/standard.Dockerfile
    secrets:
      notation-key: ${{ secrets.NOTATION_KEY }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
