name: PR Update

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # read on both needed for changes detection
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  changes:
    # Detect which files have been changed on this PR's full history
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes-pr.yaml@v4.3.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        jupyter-container:
          - './.github/workflows/on-pr-update.yaml'
          - 'containers/jupyterlab/**'
          - 'containers/custom-packages/**'
          - 'containers/files/**'
        jupyterhub-container:
          - './.github/workflows/on-pr-update.yaml'
          - 'containers/jupyterhub/**'
          - 'containers/custom-packages/**'
          - 'containers/files/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  jupyterhub-container:
    # Build the container and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).jupyterhub-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-pr-update-container.yaml@v4.3.0
    with:
      job-name: jupyterhub-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: jupyterhub
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        sudo apt update &&
        sudo apt install python3.8-venv &&
        python -m pip install --user --upgrade build &&
        python -m build --outdir ./dist ./containers/custom-packages/jupyter-cloudbeaver-proxy &&
        python -m build --outdir ./dist ./containers/custom-packages/jupyter-rsession-proxy &&
        docker build -t $IMAGE -f containers/jupyterhub/Dockerfile .
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  jupyterlab-standard-container:
    # Build the container and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).jupyter-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-pr-update-container.yaml@v4.3.0
    with:
      job-name: jupyterlab-standard-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: jupyter
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        sudo apt update &&
        sudo apt install python3.8-venv &&
        python -m pip install --user --upgrade build &&
        python -m build --outdir ./dist ./containers/custom-packages/jupyter-cloudbeaver-proxy &&
        python -m build --outdir ./dist ./containers/custom-packages/jupyter-rsession-proxy &&
        docker build -t $IMAGE -f containers/jupyterlab/standard.Dockerfile .
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
